global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'echofs-master'
    static_configs:
      - targets: ['echofs.onrender.com:443']
    scheme: https
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 10s

  - job_name: 'echofs-worker1'
    static_configs:
      - targets: ['host.docker.internal:8091']
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 5s