#!/bin/bash
export AWS_REGION="us-east-1"
export S3_BUCKET_NAME="echofs-chunks-bucket-$(date +%s)"
export DYNAMODB_FILES_TABLE="echofs-files"
export DYNAMODB_CHUNKS_TABLE="echofs-chunks"
export DYNAMODB_SESSIONS_TABLE="echofs-sessions"
export DATABASE_URL="postgres://user:password@localhost:5432/echofs?sslmode=disable"
export REDIS_ADDR="localhost:6379"
export JWT_SECRET="test-secret-key-for-development"
export LOG_LEVEL="info"
export MASTER_PORT="8080"