#!/bin/bash

echo "🚀 Starting EchoFS Workers..."
echo ""
echo "Instructions:"
echo "1. Open 3 separate terminals"
echo "2. Run these commands in each terminal:"
echo ""
echo "Terminal 1 (Worker 1):"
echo "cd echofs/Backend"
echo "go run cmd/worker1/main.go cmd/worker1/server.go"
echo ""
echo "Terminal 2 (Worker 2):"
echo "cd echofs/Backend"
echo "WORKER_ID=worker2 WORKER_PORT=8082 go run cmd/worker2/main.go cmd/worker2/server.go"
echo ""
echo "Terminal 3 (Worker 3):"
echo "cd echofs/Backend"
echo "WORKER_ID=worker3 WORKER_PORT=8083 go run cmd/worker3/main.go cmd/worker3/server.go"
echo ""
echo "Then run: ./test_workers.sh to test all workers"
echo ""
echo "Expected output from each worker:"
echo "- Starting workerX on port 808X"
echo "- Storage path: storage/workerX/chunks"
echo "- Worker HTTP server listening on port 808X"